#!/bin/bash
userName=$USER
dateTime="$(date)"
hostnameReport="$(hostname)" 
operatingSystem="$(uname -a)"
timeUp="$(uptime)"
cpuInfo="$(lscpu | grep 'Model name: '| awk '{$1=$1;print}')"
cpuSpeed="$(grep 'cpu MHz' /proc/cpuinfo | awk '{$1=$1;print}'| uniq )"
ramInfo="$(hwinfo --memory | grep 'Memory Size')"
diskInfo="$(lshw -class disk | grep 'product' | awk '{$1=$1;print}'| uniq)"
videoCard="$(hwinfo --gfxcard | grep 'Model:')"
fqdnInfo="$(sudo hostname -f)"
hostAddress="$(hostname -I)"
gatewayAddress="$(ip route | grep 'default')"
dnsAddress="$(grep -i nameserver /etc/resolv.conf |head -1| awk '{print $2}')"
interfaceName="$(hwinfo --network --short )"
ipAddresses="$(ip r)"
loggedUser="$(who -u)"
spaceDiskMounted="$(df -h)"
countProcess="$(ps)"
averageLoad="$(cat /proc/loadavg)"
allocatedMemory="$(free -h)"
listenNetwork="$(sudo ss -tunlp)"
rulesUfw="$(sudo ufw status)"
cat <<EOF

System Report generated by $userName, $dateTime
 
System Information
------------------
Hostname: $hostnameReport
OS: $operatingSystem
Uptime: $timeUp
 
Hardware Information
--------------------
cpu: $cpuInfo
Speed: $cpuSpeed
Ram: $ramInfo
Disk(s): $diskInfo
Video: $videoCard
 
Network Information
-------------------
FQDN:$fqdnInfo
Host Address: $hostAddress
Gateway IP: $gatewayAddress
DNS Server: $dnsAddress
 
InterfaceName: $interfaceName
IP Address: $ipAddresses
 
System Status
-------------
Users Logged In: $loggedUser
Disk Space: $spaceDiskMounted
Process Count: $countProcess
Load Averages: $averageLoad
Memory Allocation: $allocatedMemory
Listening Network Ports: $listenNetwork
UFW Rules: $rulesUfw

EOF
