#!/bin/bash
userName=$USER
dateTime=$DATE
hostnameReport="$(hostname)" 
operatingSystem="$(uname -a)"
timeUp="$(uptime)"
cpuInfo="$(lscpu | grep 'Model name: ')"
cpuSpeed="$(cat /proc/cpuinfo | grep 'cpu MHz' | uniq )"
ramInfo="$(hwinfo --memory | grep 'Memory Size')"
diskInfo="$(lshw -class disk | grep 'product' | uniq)"
videoCard="$(hwinfo --gfxcard | grep 'Model:')"
fqdnInfo="$(sudo hostname -f)"
hostAddress="$(hostname -I)"
gatewayAddress="$(ip route | grep 'default')"
dnsAddress="$(cat /etc/resolv.conf | grep -i nameserver |head -1| awk '{print $2}')"
interfaceName="$(hwinfo --network --short )"
ipAddresses="$(ip r)"
loggedUser="$(who -u)"
countProcess="$(ps)"
averageLoad="$(cat /proc/loadavg)"
listenNetwork="$(sudo ss -tunlp)"
cat <<EOF

System Report generated by $userName, $dateTime
 
System Information
------------------
Hostname: $hostnameReport
OS: $operatingSystem
Uptime: $timeUp
 
Hardware Information
--------------------
cpu: $cpuInfo
Speed: $cpuSpeed
Ram: $ramInfo
Disk(s): $diskInfo
Video: $videoCard
 
Network Information
-------------------
FQDN:$fqdnInfo
Host Address: $hostAddress
Gateway IP: $gatewayAddress
DNS Server: $dnsAddress
 
InterfaceName: $interfaceName
IP Address: $ipAddresses
 
System Status
-------------
Users Logged In: $loggedUser
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: $countProcess
Load Averages: $averageLoad
Memory Allocation: DATA FROM FREE
Listening Network Ports: $listenNetwork
UFW Rules: DATA FROM UFW SHOW

EOF
